/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [CustomerKey]
--      ,[GeographyKey]
--      ,[CustomerAlternateKey]
--      ,[Title]
      ,[FirstName]
--      ,[MiddleName]
      ,[LastName]
--      ,[NameStyle]
      ,[BirthDate]
--      ,[MaritalStatus]
--      ,[Suffix]
      ,[Gender]
--      ,[EmailAddress]
      ,[YearlyIncome]
--      ,[TotalChildren]
--      ,[NumberChildrenAtHome]
--      ,[EnglishEducation]
--      ,[SpanishEducation]
--      ,[FrenchEducation]
--      ,[EnglishOccupation]
--      ,[SpanishOccupation]
--      ,[FrenchOccupation]
--      ,[HouseOwnerFlag]
--      ,[NumberCarsOwned]
--      ,[AddressLine1]
--      ,[AddressLine2]
--      ,[Phone]
      ,[DateFirstPurchase]
--      ,[CommuteDistance]
      ,DimGeography.City
  FROM [AdventureWorksDW2019].[dbo].[DimCustomer]
  JOIN DimGeography ON DimGeography.GeographyKey = DimCustomer.GeographyKey
  ORDER BY CustomerKey;